---
title: "In-class practice"
author: "Yumou"
date: "2023-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Map

```{r}
library(maps)
library(tidyverse)

states = map_data("state")

states %>% ggplot(aes(x = long, y = lat)) + geom_point()

states %>% ggplot(aes(x = long, y = lat)) + geom_path(aes(group = group))
```

1. Draw a map of counties

```{r}
counties = map_data("county")

counties %>% ggplot(aes(x = long, y = lat)) + geom_path(aes(group = group))

counties %>% ggplot(aes(x = long, y = lat)) + geom_polygon(aes(group = group))
```

2. Colour all counties called “story”

```{r}
counties1 = counties %>% mutate(story = (subregion == "story"))

counties1 %>% ggplot(aes(x = long, y = lat)) + geom_polygon(aes(group = group, fill = story))

counties %>% ggplot(aes(x = long, y = lat)) + geom_path(aes(group = group)) + 
  geom_polygon(data = counties1 %>% filter(story == TRUE), 
               aes(x = long, y = lat, group = group), fill = "red")
```

3. What county names are used often?

```{r}
counties %>% ggplot(aes(x = long, y = lat)) + geom_path(aes(group = group)) + 
  geom_polygon(data = counties %>% filter(subregion == "story"), 
               aes(x = long, y = lat, group = group), fill = "red") + 
  geom_polygon(data = counties %>% filter(subregion == "washington"), 
               aes(x = long, y = lat, group = group), fill = "blue") + 
  geom_polygon(data = counties %>% filter(subregion == "jefferson"), 
               aes(x = long, y = lat, group = group), fill = "yellow") + 
  geom_polygon(data = counties %>% filter(subregion == "franklin"), 
               aes(x = long, y = lat, group = group), fill = "purple")
```

## Choropleth map

4. Draw a choropleth map of the rate of motor vehicle thefts in 2019 across the US.

```{r}
states = map_data("state")
data(fbi, package = "classdata")
fbi19 = fbi %>% filter(year == 2019)
fbi19$region = tolower(fbi19$state)
fbi.map = fbi19 %>% left_join(states, by = "region")

fbi.map %>% filter(type == "motor_vehicle_theft") %>% 
  ggplot(aes(x = long, y = lat, fill = count / population * 70000)) +
  geom_polygon(aes(group = group)) + 
  scale_fill_gradient2(
    low = "grey", 
    mid = "white", 
    high = "brown", 
    midpoint = .02
  )

```

